services:
  backend:
    build:
      context: ./needer-backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./needer-backend:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - network

  frontend:
    build:
      context: ./needer-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./needer-frontend:/app
    networks:
      - network
    restart: always

networks:
  network:
    driver: bridge
